feedback

diff --git a/evergreen.yml b/evergreen.yml
--- a/evergreen.yml
+++ b/evergreen.yml
@@ -102,8 +102,6 @@ functions:
           export MSI_FILENAME="mongoodbc-eap-$RELEASE_VERSION.msi"
           export UBUNTU_FILENAME="mongoodbc-eap-$RELEASE_VERSION.tar.gz"
 
-          # get latest mongosql tag
-          export MONGOSQL_VERSION=$(curl -s "https://api.github.com/repos/mongodb/mongosql/tags" | jq -r '.[0].name')
 
           cat <<EOT > expansions.yml
           RELEASE_VERSION: "$RELEASE_VERSION"
@@ -113,10 +111,8 @@ functions:
           UBUNTU2204_INSTALLER_PATH: "eap/mongosql-odbc-driver/ubuntu2204/$RELEASE_VERSION/release/$UBUNTU_FILENAME"
           COMPLIANCE_REPORT_NAME: "$COMPLIANCE_REPORT_NAME"
           STATIC_CODE_ANALYSIS_NAME: "$STATIC_CODE_ANALYSIS_NAME"
-          MONGOSQL_VERSION: "$MONGOSQL_VERSION"
           prepare_shell: |
             set -o errexit
-            export MONGOSQL_VERSION="$MONGOSQL_VERSION"
             export RELEASE_VERSION="$RELEASE_VERSION"
             export MSI_FILENAME="$MSI_FILENAME"
             export UBUNTU_FILENAME="$UBUNTU_FILENAME"
@@ -581,6 +577,16 @@ functions:
             exit 1
           fi
 
+          # use the latest mongosql release tag
+          MONGOSQL_VERSION=$(curl -sSfL --retry 5 "https://api.github.com/repos/mongodb/mongosql/tags" | jq -r '.[0].name')
+          echo "MONGOSQL_VERSION: $MONGOSQL_VERSION"
+          if [ -z "$MONGOSQL_VERSION" ] || [ "$MONGOSQL_VERSION" = "null" ]; then
+              echo "Error: Failed to fetch valid mongosql tags"
+              exit 1
+          fi
+          sed -i "s/^\(mongosql = {.*\)branch = \"main\"\(.*}\)/\1tag = \"$MONGOSQL_VERSION\"\2/" core/Cargo.toml
+
+
   "sign windows":
     - command: shell.exec
       type: system
@@ -663,9 +669,6 @@ functions:
         script: |
           ${prepare_shell}
 
-          # change mongosql version in core/Cargo.toml from branch to tag
-          sed -i "s/branch = \"main\"/tag = \"${MONGOSQL_VERSION}\"/" core/Cargo.toml
-
           # Compile release build
           cargo build --release
 
@@ -680,9 +683,6 @@ functions:
         working_dir: mongosql-odbc-driver
         script: |
           ${prepare_shell}
-
-          # change mongosql version in core/Cargo.toml from branch to tag
-          sed -i "s/branch = \"main\"/tag = \"${MONGOSQL_VERSION}\"/" core/Cargo.toml
 
           # Compile debug build
           cargo build
