SQL-2290: Differentiate between cluster types

diff --git a/evergreen.yml b/evergreen.yml
--- a/evergreen.yml
+++ b/evergreen.yml
@@ -84,6 +84,10 @@ functions:
             export PATH="$PATH"
             export CARGO_NET_GIT_FETCH_WITH_CLI="$CARGO_NET_GIT_FETCH_WITH_CLI"
             git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
+            export LOCAL_MDB_PORT_COM=${local_mdb_port_com}
+            export LOCAL_MDB_PORT_ENT=${local_mdb_port_ent}
+            export LOCAL_MDB_USER=${local_mdb_user}
+            export LOCAL_MDB_PWD=${local_mdb_pwd}
             export ADF_TEST_LOCAL_USER="${adf_test_local_user}"
             export ADF_TEST_LOCAL_PWD="${adf_test_local_pwd}"
             export ADF_TEST_LOCAL_AUTH_DB="${adf_test_local_auth_db}"
@@ -1516,6 +1520,51 @@ functions:
           # Stop the local ADF
           ./resources/run_adf.sh stop
           exit $EXITCODE
+          
+
+  "run ubuntu cluster type integration test":
+    command: shell.exec
+    type: test
+    params:
+      shell: bash
+      working_dir: mongosql-odbc-driver
+      script: |
+        ${prepare_shell}
+        
+        mdb_version_com="mongodb-linux-x86_64-ubuntu2204-7.0.14"
+        mdb_version_ent="mongodb-linux-x86_64-enterprise-ubuntu2204-7.0.14"
+        arch="x64"
+        
+        bash -x ./resources/start_local_mdb.sh $mdb_version_com $mdb_version_ent $arch
+  
+        # Build and move mock mongosqltranslate library
+        cargo build --package mock_mongosqltranslate
+        sudo mkdir -p /opt/mongodb/atlas-sql-odbc-driver/
+        sudo mv -f ./target/debug/libmock_mongosqltranslate.so /opt/mongodb/atlas-sql-odbc-driver/libmongosqltranslate.so
+        
+        # Enterprise test
+        cargo test --features cluster_type_tests -- cluster_type::test_determine_cluster_type_enterprise_succeeds --nocapture
+        ENTERPRISE_EXITCODE=$?
+        
+        # Community test
+        cargo test --features cluster_type_tests -- cluster_type::test_determine_cluster_type_community_fails --nocapture
+        COMMUNITY_EXITCODE=$?
+        
+        pkill mongod
+  
+        # Determine overall exit code
+        if [ $ENTERPRISE_EXITCODE -eq 0 ] && [ $COMMUNITY_EXITCODE -eq 0 ]; then
+        OVERALL_EXITCODE=0
+        else
+        OVERALL_EXITCODE=1
+        fi
+  
+        echo "Cluster test results:"
+        echo "Enterprise test exit code: $ENTERPRISE_EXITCODE"
+        echo "Community test exit code: $COMMUNITY_EXITCODE"
+        echo "Overall exit code: $OVERALL_EXITCODE"
+  
+        exit $OVERALL_EXITCODE
 
   "run macos result-set tests":
     - command: shell.exec
@@ -2027,6 +2076,8 @@ tasks:
         variants: [macos, macos-arm]
       - func: "run ubuntu integration tests"
         variants: [ubuntu2204]
+      - func: "run ubuntu cluster type integration test"
+        variants: [ ubuntu2204 ]
       # Commenting out because the following task only detects
       # memory leaks in the tests
       # - func: "run asan integration tests"
