SQL-2384: ODBC Documentation (#253)
* SQL-2384: ODBC Documentation

* feedback

diff --git a/evergreen.yml b/evergreen.yml
--- a/evergreen.yml
+++ b/evergreen.yml
@@ -14,6 +14,9 @@ command_type: system
 # 12 minutes is the longest we'll ever run
 exec_timeout_secs: 3600 # 12 minutes is the longest we'll ever run
 
+ignore:
+  - "*.md"
+
 # What to do when evergreen hits the timeout (`post:` tasks are run automatically)
 timeout:
   - command: shell.exec
@@ -1491,81 +1494,59 @@ functions:
           ./resources/run_adf.sh stop
           exit $EXITCODE
 
-  "run ubuntu mongosqltranslate integration tests":
-    - command: s3.get
-      params:
-        aws_key: ${release_aws_key}
-        aws_secret: ${release_aws_secret}
-        remote_file: mongosqltranslate/libmongosqltranslate-v${LIBMONGOSQLTRANSLATE_VERSION}-linux-x86_64.so
-        local_file: mongosql-odbc-driver/libmongosqltranslate.so
-        bucket: translators-connectors-releases
-    - command: shell.exec
-      type: test
-      params:
-        shell: bash
-        working_dir: mongosql-odbc-driver
-        script: |
-          ${prepare_shell}
-          sudo mv -f libmongosqltranslate.so target/release/libmongosqltranslate.so
-          cargo test mongosqltranslate_tests -- --nocapture
 
-  "run ubuntu cluster type integration tests":
-    - command: s3.get
-      params:
-        aws_key: ${release_aws_key}
-        aws_secret: ${release_aws_secret}
-        remote_file: mongosqltranslate/libmongosqltranslate-v${LIBMONGOSQLTRANSLATE_VERSION}-linux-x86_64.so
-        local_file: mongosql-odbc-driver/libmongosqltranslate.so
-        bucket: translators-connectors-releases
-    - command: shell.exec
-      type: test
-      params:
-        shell: bash
-        working_dir: mongosql-odbc-driver
-        script: |
-          ${prepare_shell}
+  "run ubuntu cluster type integration test":
+    command: shell.exec
+    type: test
+    params:
+      shell: bash
+      working_dir: mongosql-odbc-driver
+      script: |
+        ${prepare_shell}
 
-          mdb_version_com="mongodb-linux-x86_64-ubuntu2204-7.0.14"
-          mdb_version_ent="mongodb-linux-x86_64-enterprise-ubuntu2204-7.0.14"
-          arch="x64"
+        mdb_version_com="mongodb-linux-x86_64-ubuntu2204-7.0.14"
+        mdb_version_ent="mongodb-linux-x86_64-enterprise-ubuntu2204-7.0.14"
+        arch="x64"
 
-          # Start MongoDB instances
-          ./resources/start_local_mdb.sh $mdb_version_com $mdb_version_ent $arch
+        # Start MongoDB instances
+        ./resources/start_local_mdb.sh $mdb_version_com $mdb_version_ent $arch
 
-          # Enterprise test without library
-          cargo test --features cluster_type_tests -- \
-            cluster_type::test_determine_cluster_type_enterprise_fails_without_library --nocapture
-          ENTERPRISE_NOLIB_EXITCODE=$?
+        # Enterprise test without library
+        cargo test --features cluster_type_tests -- \
+          cluster_type::test_determine_cluster_type_enterprise_fails_without_library --nocapture
+        ENTERPRISE_NOLIB_EXITCODE=$?
 
-          # Move mongosqltranslate library to the correct location
-          sudo mv -f libmongosqltranslate.so target/release/libmongosqltranslate.so
+        # Build and move mock mongosqltranslate library
+        cargo build --package mock_mongosqltranslate
+        sudo mkdir -p /opt/mongodb/atlas-sql-odbc-driver/
+        sudo mv -f ./target/debug/libmock_mongosqltranslate.so /opt/mongodb/atlas-sql-odbc-driver/libmongosqltranslate.so
 
-          # Enterprise test with library
-          cargo test --features cluster_type_tests -- \
-            cluster_type::test_enterprise_with_library_fails_due_to_missing_sql_get_result_schema_command --nocapture
-          ENTERPRISE_LIB_EXITCODE=$?
+        # Enterprise test with library
+        cargo test --features cluster_type_tests -- \
+          cluster_type::test_enterprise_with_library_fails_due_to_missing_sql_get_result_schema_command --nocapture
+        ENTERPRISE_LIB_EXITCODE=$?
 
-          # Community test
-          cargo test --features cluster_type_tests -- cluster_type::test_determine_cluster_type_community_fails --nocapture
-          COMMUNITY_EXITCODE=$?
+        # Community test
+        cargo test --features cluster_type_tests -- cluster_type::test_determine_cluster_type_community_fails --nocapture
+        COMMUNITY_EXITCODE=$?
 
-          # Stop MongoDB instances
-          pkill mongod
+        # Stop MongoDB instances
+        pkill mongod
 
-          # Determine overall exit code
-          if [ $ENTERPRISE_NOLIB_EXITCODE -eq 0 ] && [ $ENTERPRISE_LIB_EXITCODE -eq 0 ] && [ $COMMUNITY_EXITCODE -eq 0 ]; then
-            OVERALL_EXITCODE=0
-          else
-            OVERALL_EXITCODE=1
-          fi
+        # Determine overall exit code
+        if [ $ENTERPRISE_NOLIB_EXITCODE -eq 0 ] && [ $ENTERPRISE_LIB_EXITCODE -eq 0 ] && [ $COMMUNITY_EXITCODE -eq 0 ]; then
+          OVERALL_EXITCODE=0
+        else
+          OVERALL_EXITCODE=1
+        fi
 
-          echo "Cluster test results:"
-          echo "Enterprise test without library exit code: $ENTERPRISE_NOLIB_EXITCODE"
-          echo "Enterprise test with library exit code: $ENTERPRISE_LIB_EXITCODE"
-          echo "Community test exit code: $COMMUNITY_EXITCODE"
-          echo "Overall exit code: $OVERALL_EXITCODE"
+        echo "Cluster test results:"
+        echo "Enterprise test without library exit code: $ENTERPRISE_NOLIB_EXITCODE"
+        echo "Enterprise test with library exit code: $ENTERPRISE_LIB_EXITCODE"
+        echo "Community test exit code: $COMMUNITY_EXITCODE"
+        echo "Overall exit code: $OVERALL_EXITCODE"
 
-          exit $OVERALL_EXITCODE
+        exit $OVERALL_EXITCODE
 
   "run macos result-set tests":
     - command: shell.exec
