SQL-2288: Create mongosqltranslate integration tests (#251)
* cargo.lock

* SQL-2374: Implement columns metadata logic for Direct cluster (#245)

* cargo.lock

* handle enterprise mode in get_next_metadata()

* create mongosqltranslate tests and fix logic

* fix evergreen names

* remove test flag

* rename evergreen mongosqltranslate task

* change version back to 0.0.0

* change mongosqltranslate library used in evergreen

* respond to some feedback

* add sqlcolumnsw test

* add in coll and db filters as arrays

* respond to more feedback

* fix schema handling

* make test better

* make metadata and actual values result set tests

* make from_sql_schemas_document unit tests

* rename things

* fix the handling of empty schema_catalog_doc_vec

* get correct library

* fix mongosqltranslate version in evergreen

* fix git tag handling

* rename vars

* fix message

diff --git a/evergreen.yml b/evergreen.yml
--- a/evergreen.yml
+++ b/evergreen.yml
@@ -72,6 +72,7 @@ functions:
           export COMPLIANCE_REPORT_NAME="mongo-odbc-driver_compliance_report.md"
           export STATIC_CODE_ANALYSIS_NAME="mongo-odbc-driver.sast.sarif"
           if [[ "${triggered_by_git_tag}" != "" ]]; then
+            # tag should be formatted as `v<ODBC major>.<minor>.<patch>-libv<libmongosqltranslate major>.<minor>.<patch>`
             export RELEASE_VERSION=$(echo ${triggered_by_git_tag} | cut -d'-' -f1 | sed s/v//)
             export LIBMONGOSQLTRANSLATE_VERSION=$(echo ${triggered_by_git_tag} | cut -d'-' -f2 | sed s/libv//)
           else
@@ -1305,8 +1306,7 @@ functions:
           # Logger tests will delete existing logs, in order to avoid destroying important logs from our local environment
           # the test is feature gated and will only run on evergreen.
           # Logger tests also have to run in isolation because other tests running simultaneously will "pollute" the log file the logger tests analyse.
-          cargo test --test connection_tests integration::test_driver_log_level --features evergreen_tests -- --nocapture &&
-          cargo test --package mongo-odbc-core --lib util::test_connection::test::bad_host --features bad_host -- --exact --nocapture
+          cargo test --test connection_tests integration::test_driver_log_level --features evergreen_tests -- --nocapture 
           EXITCODE=$?
           echo "****** ls -l ./target/debug/deps *******"
           ls -l ./target/debug/deps
@@ -1427,68 +1427,91 @@ functions:
           # Logger tests will delete existing logs, in order to avoid destroying important logs from our local environment
           # the test is feature gated and will only run on evergreen.
           # Logger tests also have to run in isolation because other tests running simultaneously will "pollute" the log file the logger tests analyse.
-          cargo test --test connection_tests integration::test_driver_log_level --features evergreen_tests -- --nocapture &&
-          cargo test --package mongo-odbc-core --lib util::test_connection::test::bad_host --features bad_host -- --exact --nocapture
+          cargo test --test connection_tests integration::test_driver_log_level --features evergreen_tests -- --nocapture 
 
           EXITCODE=$?
 
           # Stop the local ADF
           ./resources/run_adf.sh stop
           exit $EXITCODE
-          
 
-  "run ubuntu cluster type integration test":
-    command: shell.exec
-    type: test
-    params:
-      shell: bash
-      working_dir: mongosql-odbc-driver
-      script: |
-        ${prepare_shell}
+  "run ubuntu mongosqltranslate integration tests":
+    - command: s3.get
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        remote_file: mongosqltranslate/libmongosqltranslate-v${LIBMONGOSQLTRANSLATE_VERSION}-linux-x86_64.so
+        local_file: mongosql-odbc-driver/libmongosqltranslate.so
+        bucket: translators-connectors-releases
+    - command: shell.exec
+      type: test
+      params:
+        shell: bash
+        working_dir: mongosql-odbc-driver
+        script: |
+          ${prepare_shell}
+          sudo mkdir -p /opt/mongodb/atlas-sql-odbc-driver/
+          sudo mv -f libmongosqltranslate.so /opt/mongodb/atlas-sql-odbc-driver/libmongosqltranslate.so
+          cargo test mongosqltranslate_tests -- --nocapture        
+
+  "run ubuntu cluster type integration tests":
+    - command: s3.get
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        remote_file: mongosqltranslate/libmongosqltranslate-v${LIBMONGOSQLTRANSLATE_VERSION}-linux-x86_64.so
+        local_file: mongosql-odbc-driver/libmongosqltranslate.so
+        bucket: translators-connectors-releases
+    - command: shell.exec
+      type: test
+      params:
+        shell: bash
+        working_dir: mongosql-odbc-driver
+        script: |
+          ${prepare_shell}
         
-        mdb_version_com="mongodb-linux-x86_64-ubuntu2204-7.0.14"
-        mdb_version_ent="mongodb-linux-x86_64-enterprise-ubuntu2204-7.0.14"
-        arch="x64"
+          mdb_version_com="mongodb-linux-x86_64-ubuntu2204-7.0.14"
+          mdb_version_ent="mongodb-linux-x86_64-enterprise-ubuntu2204-7.0.14"
+          arch="x64"
         
-        # Start MongoDB instances
-        ./resources/start_local_mdb.sh $mdb_version_com $mdb_version_ent $arch
+          # Start MongoDB instances
+          ./resources/start_local_mdb.sh $mdb_version_com $mdb_version_ent $arch
         
-        # Enterprise test without library
-        cargo test --features cluster_type_tests -- \
-          cluster_type::test_determine_cluster_type_enterprise_fails_without_library --nocapture
-        ENTERPRISE_NOLIB_EXITCODE=$?
+          # Enterprise test without library
+          cargo test --features cluster_type_tests -- \
+            cluster_type::test_determine_cluster_type_enterprise_fails_without_library --nocapture
+          ENTERPRISE_NOLIB_EXITCODE=$?
         
-        # Build and move mock mongosqltranslate library
-        cargo build --package mock_mongosqltranslate
-        sudo mkdir -p /opt/mongodb/atlas-sql-odbc-driver/
-        sudo mv -f ./target/debug/libmock_mongosqltranslate.so /opt/mongodb/atlas-sql-odbc-driver/libmongosqltranslate.so
+          # Move mongosqltranslate library to the correct location
+          sudo mkdir -p /opt/mongodb/atlas-sql-odbc-driver/
+          sudo mv -f libmongosqltranslate.so /opt/mongodb/atlas-sql-odbc-driver/libmongosqltranslate.so
         
-        # Enterprise test with library
-        cargo test --features cluster_type_tests -- \
-          cluster_type::test_enterprise_with_library_fails_due_to_missing_sql_get_result_schema_command --nocapture
-        ENTERPRISE_LIB_EXITCODE=$?
+          # Enterprise test with library
+          cargo test --features cluster_type_tests -- \
+            cluster_type::test_enterprise_with_library_fails_due_to_missing_sql_get_result_schema_command --nocapture
+          ENTERPRISE_LIB_EXITCODE=$?
         
-        # Community test
-        cargo test --features cluster_type_tests -- cluster_type::test_determine_cluster_type_community_fails --nocapture
-        COMMUNITY_EXITCODE=$?
+          # Community test
+          cargo test --features cluster_type_tests -- cluster_type::test_determine_cluster_type_community_fails --nocapture
+          COMMUNITY_EXITCODE=$?
         
-        # Stop MongoDB instances
-        pkill mongod
+          # Stop MongoDB instances
+          pkill mongod
         
-        # Determine overall exit code
-        if [ $ENTERPRISE_NOLIB_EXITCODE -eq 0 ] && [ $ENTERPRISE_LIB_EXITCODE -eq 0 ] && [ $COMMUNITY_EXITCODE -eq 0 ]; then
-          OVERALL_EXITCODE=0
-        else
-          OVERALL_EXITCODE=1
-        fi
+          # Determine overall exit code
+          if [ $ENTERPRISE_NOLIB_EXITCODE -eq 0 ] && [ $ENTERPRISE_LIB_EXITCODE -eq 0 ] && [ $COMMUNITY_EXITCODE -eq 0 ]; then
+            OVERALL_EXITCODE=0
+          else
+            OVERALL_EXITCODE=1
+          fi
         
-        echo "Cluster test results:"
-        echo "Enterprise test without library exit code: $ENTERPRISE_NOLIB_EXITCODE"
-        echo "Enterprise test with library exit code: $ENTERPRISE_LIB_EXITCODE"
-        echo "Community test exit code: $COMMUNITY_EXITCODE"
-        echo "Overall exit code: $OVERALL_EXITCODE"
+          echo "Cluster test results:"
+          echo "Enterprise test without library exit code: $ENTERPRISE_NOLIB_EXITCODE"
+          echo "Enterprise test with library exit code: $ENTERPRISE_LIB_EXITCODE"
+          echo "Community test exit code: $COMMUNITY_EXITCODE"
+          echo "Overall exit code: $OVERALL_EXITCODE"
         
-        exit $OVERALL_EXITCODE
+          exit $OVERALL_EXITCODE
 
   "run macos result-set tests":
     - command: shell.exec
@@ -1561,8 +1584,7 @@ functions:
           # Logger tests will delete existing logs, in order to avoid destroying important logs from our local environment
           # the test is feature gated and will only run on evergreen.
           # Logger tests also have to run in isolation because other tests running simultaneously will "pollute" the log file the logger tests analyse.
-          cargo test --test connection_tests integration::test_driver_log_level --features evergreen_tests,definitions/iodbc,cstr/utf32 -- --nocapture &&
-          cargo test --package mongo-odbc-core --lib util::test_connection::test::bad_host --features definitions/iodbc,cstr/utf32,bad_host -- --exact --nocapture
+          cargo test --test connection_tests integration::test_driver_log_level --features evergreen_tests,definitions/iodbc,cstr/utf32 -- --nocapture 
           EXITCODE=$?
 
           # Stop the local ADF
@@ -1647,8 +1669,7 @@ functions:
           # Logger tests will delete existing logs, in order to avoid destroying important logs from our local environment
           # the test is feature gated and will only run on evergreen.
           # Logger tests also have to run in isolation because other tests running simultaneously will "pollute" the log file the logger tests analyse.
-          cargo test --target x86_64-unknown-linux-gnu --test connection_tests integration::test_driver_log_level --features evergreen_tests -- --nocapture &&
-          cargo test --target x86_64-unknown-linux-gnu --package mongo-odbc-core --lib util::test_connection::test::bad_host --features bad_host -- --exact --nocapture
+          cargo test --target x86_64-unknown-linux-gnu --test connection_tests integration::test_driver_log_level --features evergreen_tests -- --nocapture 
           EXITCODE=$?
 
           # Stop the local ADF
@@ -2026,8 +2047,10 @@ tasks:
       - func: "generate github token"
       - func: "run ubuntu integration tests"
         variants: [ubuntu2204]
-      - func: "run ubuntu cluster type integration test"
-        variants: [ ubuntu2204 ]
+      - func: "run ubuntu cluster type integration tests"
+        variants: [ubuntu2204]
+      - func: "run ubuntu mongosqltranslate integration tests"
+        variants: [ubuntu2204]
       # Commenting out because the following task only detects
       # memory leaks in the tests
       # - func: "run asan integration tests"
