SQL-2094: Run static code analysis for ODBC (#218)
* cargo.lock

* create static code analysis

* fix naming

* add semgrep_app_token

* Update evergreen.yml

Co-authored-by: Matthew Chiaravalloti <matthew.chiaravalloti@mongodb.com>

* remove venv='venv'

---------

Co-authored-by: Matthew Chiaravalloti <matthew.chiaravalloti@mongodb.com>

diff --git a/evergreen.yml b/evergreen.yml
--- a/evergreen.yml
+++ b/evergreen.yml
@@ -1582,6 +1582,47 @@ functions:
         permissions: public-read
         content_type: application/json
 
+  "static code analysis":
+    - command: shell.exec
+      type: test
+      params:
+        shell: bash
+        working_dir: mongosql-odbc-driver
+        script: |
+          ${prepare_shell}
+          export SEMGREP_APP_TOKEN=${semgrep_app_token}
+          echo "Running static code analysis with Semgrep..."
+
+          # Setup or use the existing virtualenv for semgrep
+          if [[ -f "venv/bin/activate" ]]; then
+              echo 'using existing virtualenv'
+              . venv/bin/activate
+          else
+              echo 'Creating new virtualenv'
+              python3 -m virtualenv venv
+              echo 'Activating new virtualenv'
+              . venv/bin/activate
+          fi
+          python3 -m pip install semgrep
+          # Confirm semgrep version
+          semgrep --version
+          set +e
+          semgrep --config p/rust --sarif --exclude "integration_test" --verbose --error --severity=ERROR --sarif-output=mongo-odbc-driver.sast.sarif > mongo-odbc-driver.sast.cmd.verbose.out 2>&1
+          SCAN_RESULT=$?
+          set -e
+          # Exit with a failure if the scan found an issue
+          exit $SCAN_RESULT
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_files_include_filter:
+          - mongo-odbc-driver.sast.*
+        remote_file: mongosql-odbc-driver/artifacts/${version_id}/${build_variant}/ssdlc/
+        content_type: text/plain
+        bucket: mciuploads
+        permissions: public-read
+
 pre:
   - func: "fetch source"
   - func: "generate expansions"
@@ -1792,6 +1833,11 @@ tasks:
       - func: "upload release"
       - func: "upload debug"
 
+  - name: semgrep
+    exec_timeout_secs: 3600 # 1h
+    commands:
+      - func: "static code analysis"
+
 task_groups:
   - name: windows-windows-test-unit-group
     setup_group_can_fail_task: false
@@ -1840,11 +1886,11 @@ buildvariants:
       - name: rustfmt
       - name: asan-compile
 
-buildvariants:
   - name: code-quality-security
     display_name: "Code quality and Security"
     run_on: [ubuntu2204-small]
     tasks:
+      - name: semgrep
       - name: sbom
 
   - name: windows-64
